const images = {
    a: require('../assets/images/a.png'),
    b: require('../assets/images/b.png'),
    c: require('../assets/images/c.png'),
    d: require('../assets/images/d.png'),
    circle: require('../assets/images/circle.png'),
    fifth1: require('../assets/images/fifth1.png'),
    fifth2: require('../assets/images/fifth2.png'),
    fifth3: require('../assets/images/fifth3.png'),
    // fifth4: require('../assets/images/fifth4.jpg'),
    // fifthplay1: require('../assets/images/fifthplay1.jpg'),
    // fifthplay2: require('../assets/images/fifthplay2.jpg'),
    // first: require('../assets/images/first.jpg'),
    // fourthcircle: require('../assets/images/fourthcircle.jpg'),
    // fourthrect: require('../assets/images/fourthrect.png'),
    // fourthredcir: require('../assets/images/fourthredcir.png'),
    fourthredline: require('../assets/images/fourthredline.png'),
    line: require('../assets/images/line.png'),
    logo: require('../assets/images/logo.png'),
    // logos: require('../assets/images/logos.jpg'),
    r1: require('../assets/images/r1.png'),
    // r2: require('../assets/images/r2.png'),
    r3: require('../assets/images/r3.png'),
    r4: require('../assets/images/r4.png'),
    r5: require('../assets/images/r5.png'),
    red: require('../assets/images/red.png'),
    second: require('../assets/images/second.png'),
    seventh1: require('../assets/images/seventh1.png'),
    seventh2: require('../assets/images/seventh2.png'),
    seventh3: require('../assets/images/seventh3.png'),
    seventhrect: require('../assets/images/seventhrect.png'),
    seventhrect2: require('../assets/images/seventhrect2.png'),
    sixth1: require('../assets/images/sixth1.png'),
    sixth2: require('../assets/images/sixth2.png'),
    sixth3: require('../assets/images/sixth3.png'),
    sixthline: require('../assets/images/sixthline.png'),
    sixthredcir: require('../assets/images/sixthredcir.png'),
    sixthredline: require('../assets/images/sixthredline.png'),
    third1: require('../assets/images/third1.png'),
    third2: require('../assets/images/third2.png'),
    third3: require('../assets/images/third3.png'),
    third4: require('../assets/images/third4.png'),
    thirdcircle: require('../assets/images/thirdcircle.png'),
    thirdrect: require('../assets/images/thirdrect.png'),
    wavy: require('../assets/images/wavy.png'),
    // instagramId: require('../assets/images/instagram_id.png'),
    pic1: require('../assets/images/pic1.png'),
    pic2: require('../assets/images/pic2.png'),
    pic3: require('../assets/images/pic3.png'),
    pic4: require('../assets/images/pic4.jpeg'),
    rect: require('../assets/images/rect.png'),
    rect2: require('../assets/images/rect2.png'),
    ellipse: require('../assets/images/Ellipse.jpg'),
    main: require('../assets/images/blogmain.jpg'),
    b1: require('../assets/images/1.jpg'),
    b2: require('../assets/images/2.jpg'),
    b3: require('../assets/images/3.jpg'),
    b4: require('../assets/images/4.jpg'),
    b5: require('../assets/images/5.jpg'),
    b6: require('../assets/images/6.jpg'),
    b7: require('../assets/images/7.jpg'),
    b8: require('../assets/images/8.jpg'),
    b9: require('../assets/images/9.jpg'),
    icon1: require('../assets/icons/sicon1.png'),
    icon2: require('../assets/icons/sicon2.png')



};

// instagram images
for (let i = 0; i < 8; i++) {
    images['instagram' + (i + 1)] = require(`../assets/images/instagram_${i + 1}.png`)
};

export default images;